#!/usr/bin/env python3
"""
CSV to Image Converter for 5G NR demodulation data.
Converts CSV files generated by demodulate_cli.py back to resource grid images.
"""

import sys
import argparse
import csv
import numpy as np
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed
from threading import Lock

from visualization import plot_resource_grid

# Global lock for matplotlib plotting (not thread-safe)
plot_lock = Lock()


def load_csv_file(csv_file: str, verbose: bool = False):
    """
    Load demodulation data from CSV file.
    
    Args:
        csv_file: Path to CSV file
        verbose: Show detailed information
    
    Returns:
        Dictionary with metadata and grid_display, or None if failed
    """
    try:
        with open(csv_file, 'r') as f:
            reader = csv.reader(f)
            
            # Parse metadata section
            metadata = {}
            in_metadata = False
            in_grid = False
            grid_data = []
            
            for row in reader:
                if not row:
                    continue
                
                # Metadata section
                if row[0] == '# DEMODULATION METADATA':
                    in_metadata = True
                    continue
                
                if in_metadata and not row[0].startswith('#'):
                    if len(row) >= 2:
                        key = row[0]
                        value = row[1]
                        
                        # Parse specific fields
                        if key in ['Cell ID', 'NID1', 'NID2', 'Strongest SSB', 'Timing Offset (samples)']:
                            metadata[key] = int(value)
                        elif key in ['Potencia (dB)', 'SNR (dB)', 'Freq Offset (Hz)', 
                                   'Power (dB)', 'Subcarrier Spacing (kHz)', 
                                   'Sample Rate (Hz)', 'GSCN']:
                            metadata[key] = float(value)
                        else:
                            metadata[key] = value
                
                # Resource grid section
                if row[0] == '# RESOURCE GRID':
                    in_grid = True
                    in_metadata = False
                    continue
                
                if in_grid:
                    # Skip comment rows
                    if row[0].startswith('#'):
                        continue
                    
                    # Skip header row (Subcarrier, Symbol_0, ...)
                    if row[0] in ['Subcarrier']:
                        continue
                    
                    # Parse data rows (SC_0, value1, value2, ...)
                    if row[0].startswith('SC_'):
                        values = [float(val) for val in row[1:]]
                        grid_data.append(values)
            
            if not grid_data:
                raise ValueError("No resource grid data found in CSV")
            
            # Convert to numpy array
            grid_display = np.array(grid_data, dtype=np.float32)
            
            # Extract Cell ID and SNR for plotting
            cell_id = metadata.get('Cell ID', 0)
            snr_db = metadata.get('SNR (dB)', 0.0)
            
            if verbose:
                print(f"✓ Loaded: {Path(csv_file).name}")
                print(f"  Cell ID: {cell_id}, SNR: {snr_db:.1f} dB")
                print(f"  Grid shape: {grid_display.shape[0]} subcarriers × {grid_display.shape[1]} symbols")
            
            return {
                'grid_display': grid_display,
                'cell_id': cell_id,
                'snr_db': snr_db,
                'metadata': metadata,
                'filename': Path(csv_file).name
            }
            
    except Exception as e:
        error_msg = str(e)
        if verbose:
            print(f"\n✗ ERROR loading {Path(csv_file).name}: {error_msg}")
            import traceback
            traceback.print_exc()
        else:
            print(f"✗ {Path(csv_file).name}: ERROR - {error_msg[:80]}")
        
        return None


def convert_csv_to_image(csv_file: str,
                        output_folder: str = None,
                        show_axes: bool = False,
                        verbose: bool = False) -> bool:
    """
    Convert a single CSV file to resource grid image.
    
    Args:
        csv_file: Path to CSV file
        output_folder: Output folder for image (None = same as CSV)
        show_axes: Show axes and labels in image
        verbose: Show detailed information
    
    Returns:
        True if successful, False otherwise
    """
    # Load CSV data
    data = load_csv_file(csv_file, verbose=verbose)
    
    if data is None:
        return False
    
    # Determine output folder
    if output_folder is None:
        output_folder = Path(csv_file).parent
    
    # Generate image filename
    csv_path = Path(csv_file)
    if csv_path.stem.endswith('_data'):
        image_name = csv_path.stem[:-5] + '_resource_grid'
    else:
        image_name = csv_path.stem + '_resource_grid'
    
    # Plot resource grid (with lock for thread safety)
    try:
        with plot_lock:
            plot_resource_grid(
                data['grid_display'],
                data['cell_id'],
                data['snr_db'],
                output_folder=output_folder,
                filename=image_name,
                verbose=verbose,
                show_axes=show_axes
            )
        
        if not verbose:
            print(f"✓ {Path(csv_file).name} → {image_name}.png")
        
        return True
        
    except Exception as e:
        error_msg = str(e)
        if verbose:
            print(f"\n✗ ERROR generating image: {error_msg}")
            import traceback
            traceback.print_exc()
        else:
            print(f"✗ {Path(csv_file).name}: Image generation failed - {error_msg[:80]}")
        
        return False


def convert_folder(folder_path: str,
                  output_folder: str = None,
                  pattern: str = "*.csv",
                  show_axes: bool = False,
                  verbose: bool = False,
                  num_threads: int = 4):
    """
    Convert all CSV files in a folder to resource grid images.
    
    Args:
        folder_path: Path to folder with CSV files
        output_folder: Output folder for images (None = same as CSV folder)
        pattern: File pattern to match
        show_axes: Show axes and labels in images
        verbose: Show detailed information
        num_threads: Number of threads for parallel processing
    
    Returns:
        Dictionary with statistics
    """
    folder = Path(folder_path)
    csv_files = sorted(folder.glob(pattern))
    
    if verbose:
        print(f"Found {len(csv_files)} CSV files matching '{pattern}' in {folder_path}")
    else:
        print(f"\nProcessing {len(csv_files)} CSV files...")
    
    successful = 0
    failed = 0
    
    # Lock for thread-safe console output
    print_lock = Lock()
    
    def process_single_file(csv_file):
        """Helper function to process one file in a thread."""
        result = convert_csv_to_image(
            str(csv_file),
            output_folder=output_folder,
            show_axes=show_axes,
            verbose=verbose
        )
        return csv_file, result
    
    # Parallel processing with ThreadPoolExecutor
    if num_threads > 1:
        with ThreadPoolExecutor(max_workers=num_threads) as executor:
            # Submit all jobs
            futures = {executor.submit(process_single_file, csv_file): csv_file 
                      for csv_file in csv_files}
            
            # Process results as they complete
            for future in as_completed(futures):
                csv_file, result = future.result()
                
                with print_lock:
                    if result:
                        successful += 1
                    else:
                        failed += 1
                
                if verbose:
                    with print_lock:
                        print()  # Blank line between files in verbose mode
    else:
        # Sequential processing (1 thread)
        for csv_file in csv_files:
            result = convert_csv_to_image(
                str(csv_file),
                output_folder=output_folder,
                show_axes=show_axes,
                verbose=verbose
            )
            
            if result:
                successful += 1
            else:
                failed += 1
            
            if verbose:
                print()  # Blank line between files in verbose mode
    
    print(f"\n{'='*70}")
    print(f"Conversion completed: {successful} successful, {failed} failed")
    print("="*70)
    
    if output_folder:
        print(f"✓ Images saved to: {output_folder}/")
    
    return {
        'successful': successful,
        'failed': failed,
        'total': len(csv_files)
    }


def main():
    parser = argparse.ArgumentParser(
        description='CSV to Image Converter - Convert demodulation CSV files to resource grid images'
    )
    
    parser.add_argument(
        'input',
        type=str,
        help='CSV file or folder with CSV files'
    )
    
    parser.add_argument(
        '-o', '--output',
        type=str,
        default=None,
        help='Output folder for images (default: same folder as CSV files)'
    )
    
    parser.add_argument(
        '--pattern',
        type=str,
        default='*.csv',
        help='File pattern for folders (default: *.csv)'
    )
    
    parser.add_argument(
        '--show-axes',
        action='store_true',
        help='Show axes and labels in images (default: no axes)'
    )
    
    parser.add_argument(
        '--verbose',
        action='store_true',
        help='Show detailed processing information (default: quiet mode)'
    )
    
    parser.add_argument(
        '--threads',
        type=int,
        default=4,
        help='Number of threads for parallel processing (default: 4)'
    )
    
    args = parser.parse_args()
    
    input_path = Path(args.input)
    
    if not input_path.exists():
        print(f"✗ Error: {args.input} does not exist")
        sys.exit(1)
    
    # Process file or folder
    if input_path.is_file():
        result = convert_csv_to_image(
            str(input_path),
            output_folder=args.output,
            show_axes=args.show_axes,
            verbose=args.verbose
        )
        
        if result:
            print(f"\n✓ Conversion completed successfully")
            if args.output:
                print(f"✓ Image saved to: {args.output}/")
            sys.exit(0)
        else:
            print(f"\n✗ Conversion failed")
            sys.exit(1)
    
    elif input_path.is_dir():
        summary = convert_folder(
            str(input_path),
            output_folder=args.output,
            pattern=args.pattern,
            show_axes=args.show_axes,
            verbose=args.verbose,
            num_threads=args.threads
        )
        
        sys.exit(0 if summary['failed'] == 0 else 2)
    
    else:
        print(f"✗ Error: {args.input} is not a valid file or folder")
        sys.exit(1)


if __name__ == '__main__':
    main()
